<?php
/**
 * @author Liao Gengling <liaogling@gmail.com>
 */
return [
    'yearTablet' => [
        0 => 62,
        1 => 167,
        2 => 12,
        3 => 117,
        4 => 222,
        5 => 67,
        6 => 172,
        7 => 17,
        8 => 122,
        9 => 227,
        10 => 72,
        11 => 177,
        12 => 22,
        13 => 127,
        14 => 232,
        15 => 77,
        16 => 182,
        17 => 27,
        18 => 132,
        19 => 237,
        20 => 82,
        21 => 187,
        22 => 32,
        23 => 137,
        24 => 242,
        25 => 87,
        26 => 192,
        27 => 37,
        28 => 142,
        29 => 247,
        30 => 92,
        31 => 197,
        32 => 42,
        33 => 147,
        34 => 252,
        35 => 97,
        36 => 202,
        37 => 47,
        38 => 152,
        39 => 257,
        40 => 102,
        41 => 207,
        42 => 52,
        43 => 157,
        44 => 2,
        45 => 107,
        46 => 212,
        47 => 57,
        48 => 162,
        49 => 7,
        50 => 112,
        51 => 217,
    ],
    
    'monthTablet' => [
        1 => 0,
        2 => 31,
        3 => 59,
        4 => 90,
        5 => 120,
        6 => 151,
        7 => 181,
        8 => 212,
        9 => 243,
        10 => 13,
        11 => 44,
        12 => 74
    ],
    // 图腾
    'seals' => [
        1 => [
            'number' => 1,
            'name' => '紅龍', // 
            'feature' => '滋养、培育', // 动能
            'function' => '存在', // 功能
            'essence' => '诞生', // 本质
            'effect' => '輸入通知設定', // 程式作用
            'position' => '右手食指', // 对应身体小关节的位置
        ], 
        2 => [
            'number' => 2,
            'name' => '白風',
            'feature' => '',
            'function' => '呼吸',
            'essence' => '心灵',
            'effect' => '輸入通知設定',
            'position' => '',
        ], 
        3 => [
            'number' => 3,
            'name' => '藍夜',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '輸入通知設定',
            'position' => '',
        ],
        4 => [
            'number' => 4,
            'name' => '黃種子',
            'feature' => '',
            'function' => '',
            'essence' => '輸入通知設定',
            'effect' => '',
            'position' => '',
        ],
        5 => [
            'number' => 5,
            'name' => '紅蛇',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '存取記憶設定',
            'position' => '',
        ],
        6 => [
            'number' => 6,
            'name' => '白世界橋',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '存取記憶設定',
            'position' => '',
        ],
        7 => [
            'number' => 7,
            'name' => '藍手',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '存取記憶設定',
            'position' => '',
        ],
        8 => [
            'number' => 8,
            'name' => '黃星星',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '存取記憶設定',
            'position' => '',
        ],
        9 => [
            'number' => 9,
            'name' => '红月',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '程式運作過程',
            'position' => '',
        ],
        10 => [
            'number' => 10,
            'name' => '白狗',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '程式運作過程',
            'position' => '',
        ],
        11 => [
            'number' => 11,
            'name' => '藍猴',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '程式運作過程',
            'position' => '',
        ],
        12 => [
            'number' => 12,
            'name' => '黄人',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '程式運作過程',
            'position' => '',
        ],
        13 => [
            'number' => 13,
            'name' => '紅天行者',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '輸出傳送設定',
            'position' => '',
        ],
        14 => [
            'number' => 14,
            'name' => '白巫師',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '輸出傳送設定',
            'position' => '',
        ],
        15 => [
            'number' => 15,
            'name' => '藍鷹',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '輸出傳送設定',
            'position' => '',
        ],
        16 => [
            'number' => 16,
            'name' => '黃戰士',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '輸出傳送設定',
            'position' => '',
        ],
        17 => [
            'number' => 17,
            'name' => '紅地球',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '自動調節校準的母體',
            'position' => '',
        ],
        18 => [
            'number' => 18,
            'name' => '白鏡子',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '自動調節校準的母體',
            'position' => '',
        ],
        19 => [
            'number' => 19,
            'name' => '藍暴風雨',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '自動調節校準的母體',
            'position' => '',
        ],
        20 => [
            'number' => 20,
            'name' => '黃太陽',
            'feature' => '',
            'function' => '',
            'essence' => '',
            'effect' => '自動調節校準的母體',
            'position' => '',
        ]
    ],
    
    'colors' => [
        1 => [
            'number' => 1,
            'color' => '粉色',
        ],
        2 => [
            'number' => 2,
            'color' => '白色',
        ],
        3 => [
            'number' => 3,
            'color' => '蓝色',
        ],
        4 => [
            'number' => 4,
            'color' => '黄色',
        ],
        5 => [
            'number' => 5,
            'color' => '绿色',
        ]
    ]
];